stages:
  - Build
  - Test
  - Deploy 

job_name: Build_code
  stage: Build
    image: image name
    script:
      echo "this is practice"
services:
  - name: super/sql:latest
    command: ["/usr/bin/super-sql", "run"]
---
stages:
  - build
  - test
  - deploy

job 0:
  stage: .pre
  script: make something useful before build stage

job 1:
  stage: build
  script: make build dependencies

job 2:
  stage: build
  script: make build artifacts
  only: 
    - master # Run this job only when something is commited to master branch

job 3:
  stage: test
  script: make test

job 4:
  stage: deploy
  script: make deploy

job 5:
  stage: .post
  script: make something useful at the end of pipeline
...
# only defines the names of branches and tags for which the job will run.
# except defines the names of branches and tags for which the job will not run.
job:
  script: echo 'test'
  only: ['branches', 'tags']